cnp_settings:
  representation_size: 32
  encoder_hidden_layers:
  - 32
  - 64
  - 64
  - 48
  decoder_hidden_layers:
  - 32
  - 64
  - 64
  - 48
  context_ratio: 0.33
  context_is_subset: true
  batch_size_train: 1000
  files_per_batch_train: 10
  files_per_batch_predict: 1
  dataloader_number_of_workers: 1
  dataloader_prefetch_factor: 4
  dataloader_pin_memory: false
  dataloader_persistent_workers: false
  split_ratio:
  - 0.6
  - 0.2
  - 0.2
  training:
    use_staged_training: false
    phase1:
      training_epochs: 1
      mixup_ratio: 0.0
      mixup_margin: 0.0
      use_beta:
      - 0.1
      - 0.1
      learning_rate: 0.001
      loss:
        prior_pos: true
        alpha_pos: 0.2
        alpha_neg: null
        gamma_pos: 2.0
        gamma_neg: 2.0
        lambda_fp: 0.0
        tau_fp: 0.0
        reduction: mean
    phase2:
      training_epochs: 0
      learning_rate: 0.001
      weight_false_positives: 0.0
      weight_true_positives: 0.0
feature_settings:
  use_normalization: zscore
  feature_size: 30
  target_size: 1

simulation_settings:
  theta_headers:
  - metallicity
  - envelope_eff_alpha
  - sigma_bh
  - sigma_ns
  theta_headers_plot:
  - metallicity
  - $\alpha_{CE}$
  - $\sigma_{BH}$
  - $\sigma_{SN}$
  phi_labels:
  - CH_on_MS(1)
  - CH_on_MS(2)
  - Eccentricity@ZAMS
  - Equilibrated_At_Birth
  - Evolution_Status
  - Mass@ZAMS(1)
  - Mass@ZAMS(2)
  - Merger
  - Merger_At_Birth
  - Metallicity@ZAMS(1)
  - Metallicity@ZAMS(2)
  - Omega@ZAMS(1)
  - Omega@ZAMS(2)
  - PO_CE_Alpha
  - PO_LBV_Factor
  - PO_Sigma_Kick_ECSN
  - PO_Sigma_Kick_USSN
  - PO_WR_Factor
  - SN_Kick_Magnitude_Random_N
  - SemiMajorAxis@ZAMS
  - Stellar_Type(1)
  - Stellar_Type(2)
  - Stellar_Type@ZAMS(1)
  - Stellar_Type@ZAMS(2)
  target_headers:
  - BBH Events
  target_headers_plot: $\hat{\epsilon}$
  target_range:
  - 0
  - 1
  signal_condition:
  - BBH Events==1
  theta_min:
  - 0.0001
  - 0
  - 0
  - 0
  theta_max:
  - 0.031
  - 10
  - 1000
  - 1000
  observed_rate: 17
  y_scaling: 3142.6685399999997
  lf_cost: 1
  hf_cost: 1000
mfgp_settings:
  noise:
    lf: 0.021
    hf: 0.0
pce_settings:
  polynomial_order: 4
  priors:
    lf:
      sigma_coeffs_prior_type: default
      sigma_coeffs: 0.1
      sigma_y: 0.021
    hf:
      mu_rho: 0.49466
      sigma_rho: 0.15313
      sigma_coeffs_prior_type: default
      sigma_coeffs_delta: 0.1
      sigma_y: 0.006
path_settings:
  version: v1.3.4
  path_to_files_train: ../in/data/lf/v1.3/training_cnp
  path_to_files_predict:
  - ../in/data/lf/v1.3/training_regression
  iteration:
  - -1
  fidelity:
  - 0
  path_out_cnp: ../out/cnp
  path_out_hcanp: ../out/hcacnp
  path_out_mfgp: ../out/mfgp
  path_out_pce: ../out/pce
